# Generated by Django 5.0.4 on 2024-08-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_text',
            field=models.TextField(default='user', max_length=100),
        ),
    ]
