# Generated by Django 5.0.4 on 2024-08-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_bio_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio_text',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
